// @flow
import React, { PureComponent as Component } from "react";
import {
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ArrowLeft,
  Play,
  Pause,
  Search,
  Check,
  Lock,
  SendHorizontal,
  MousePointer,
  Menu,
  List,
  LayoutGrid,
  SlidersHorizontal,
  Settings,
  Sun,
  SunMedium,
  Moon,
  Users,
  MessageCircle,
  Trophy,
  Star,
  StarOff,
  Flame,
  Coffee,
  Code,
  ChevronsUpDown,
  Zap,
  Hourglass,
  Maximize2,
  Minimize2,
  Loader2,
  Download,
  ExternalLink,
  MessageSquare,
  Ban,
  HeartHandshake,
  Heart,
  CircleX,
  Crown,
  Cpu,
  Activity,
  Medal,
  Info,
  BadgeInfo,
  HatGlasses,
  DoorOpen,
  MessagesSquare,
  Compass,
  MessageSquareOff,
  Mail,
  Trash2,
  Reply,
  AlertTriangle,
  Bell,
  Swords,
  Sword,
  Shield,
  ShieldCheck,
  ShieldOff,
  Sparkle,
  Wrench,
  Smile,
  Leaf,
  Calendar,
  CalendarCheck,
  Globe,
  Gamepad2,
  LogOut,
  User,
  Undo2,
  MessageSquareDashed,
  Palette,
  Plus,
  Minus,
  X,
  Presentation,
  GraduationCap,
  BookOpen,
  Pencil,
  Eye,
  UserPlus,
  CirclePlus,
  Library,
  Tag,
  Target,
  Shuffle,
  Radar,
  Snail,
  Clock,
  MoveDiagonal2,
  CircleDot,
  MessageSquareText,
  Triangle,
  Square,
  Circle,
  BrainCircuit,
  LoaderCircle,
} from "lucide-react";

// Map Font Awesome icon names → Lucide components (backward-compat shim)
const ICON_MAP: { [string]: any } = {
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "angle-down": ChevronDown,
  "fast-backward": ChevronsLeft,
  "fast-forward": ChevronsRight,
  "arrow-left": ArrowLeft,
  play: Play,
  pause: Pause,
  search: Search,
  check: Check,
  lock: Lock,
  "paper-plane": SendHorizontal,
  "hand-pointer-o": MousePointer,
  bars: Menu,
  list: List,
  "layout-grid": LayoutGrid,
  sliders: SlidersHorizontal,
  settings: Settings,
  cog: Settings,
  "sun-o": Sun,
  "sun-medium": SunMedium,
  "moon-o": Moon,
  users: Users,
  "comment-o": MessageCircle,
  trophy: Trophy,
  star: Star,
  "star-o": Star,
  "star-off": StarOff,
  flame: Flame,
  coffee: Coffee,
  code: Code,
  "chevrons-up-down": ChevronsUpDown,
  bolt: Zap,
  "hourglass-o": Hourglass,
  expand: Maximize2,
  compress: Minimize2,
  download: Download,
  "external-link": ExternalLink,
  spinner: Loader2,
  "message-square": MessageSquare,
  ban: Ban,
  "heart-handshake": HeartHandshake,
  heart: Heart,
  "heart-o": Heart,
  "circle-x": CircleX,
  crown: Crown,
  cpu: Cpu,
  activity: Activity,
  medal: Medal,
  info: Info,
  "badge-info": BadgeInfo,
  "hat-glasses": HatGlasses,
  "door-open": DoorOpen,
  "messages-square": MessagesSquare,
  compass: Compass,
  "message-square-off": MessageSquareOff,
  mail: Mail,
  trash: Trash2,
  reply: Reply,
  "alert-triangle": AlertTriangle,
  bell: Bell,
  swords: Swords,
  sword: Sword,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  sparkle: Sparkle,
  astroid: Sparkle,
  wrench: Wrench,
  smile: Smile,
  leaf: Leaf,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  globe: Globe,
  gamepad: Gamepad2,
  "log-out": LogOut,
  user: User,
  "undo-2": Undo2,
  "message-square-dashed": MessageSquareDashed,
  palette: Palette,
  plus: Plus,
  minus: Minus,
  x: X,
  presentation: Presentation,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  pencil: Pencil,
  eye: Eye,
  "user-plus": UserPlus,
  "circle-plus": CirclePlus,
  library: Library,
  tag: Tag,
  target: Target,
  shuffle: Shuffle,
  radar: Radar,
  snail: Snail,
  clock: Clock,
  "move-diagonal": MoveDiagonal2,
  "circle-dot": CircleDot,
  "message-square-text": MessageSquareText,
  triangle: Triangle,
  square: Square,
  circle: Circle,
  "brain-circuit": BrainCircuit,
  loader: LoaderCircle,
};

type Props = {
  name: string,
  size?: number,
  color?: string,
  strokeWidth?: number,
  className?: string,
  style?: Object,
};

export class Icon extends Component<Props> {
  render() {
    const {
      name,
      size = 16,
      color,
      strokeWidth,
      className,
      style,
    } = this.props;
    const LucideIcon = ICON_MAP[name];

    if (!LucideIcon) {
      return <span className={"Icon Icon--unknown Icon--" + name} />;
    }

    const props: Object = { size, "aria-hidden": true };
    if (color) {
      props.color = color;
    }
    if (strokeWidth !== null && strokeWidth !== undefined) {
      props.strokeWidth = strokeWidth;
    }
    if (style) {
      props.style = style;
    }

    // Construct class name: default is "Icon", add spinner, and append any custom className
    let classNames = "Icon";
    if (name === "spinner") {
      classNames += " Icon--spin";
    }
    if (className) {
      classNames += " " + className;
    }
    props.className = classNames;

    if (name === "star" || name === "heart-handshake" || name === "heart") {
      props.fill = "currentColor";
    }

    return <LucideIcon {...props} />;
  }
}
